    
    - name: Update & Install ntp
      apt:
        update_cache: true
        pkg:
          - ntp

    - name: Enable & Start Unattended Upgrades
      service:
        name: ntp
        state: started
        enabled: yes
      register: ntp
    - debug: var=ntp.stdout_lines
    
    - name: Change timezone to UTC & Check the status of Timectl-NTP
      shell: |
        timedatectl set-timezone UTC
        timedatectl set-ntp true
        timedatectl status
      register: timedatectl
    - debug: var=timedatectl