  
    - name: Download Crowdsec repo
      shell: curl -s https://packagecloud.io/install/repositories/crowdsec/crowdsec/script.deb.sh | sudo bash
      when: ansible_os_family == 'Debian'
    
    - name: Crowdsec - Update & Install ( Debian-Based)
      apt:
        update_cache: true
        pkg:
          - crowdsec 
          - crowdsec-firewall-bouncer-iptables
        state: latest
      when: ansible_os_family == 'Debian'

    - name: Enable & Start Crowdsec
      service:
        name: crowdsec
        state: started
        enabled: yes
      when: ansible_os_family == 'Debian'