    - name: Add Nginx keys and Repo. 
      shell: |
            curl https://nginx.org/keys/nginx_signing.key | gpg --dearmor | sudo tee /usr/share/keyrings/nginx-archive-keyring.gpg > /dev/null
            gpg --dry-run --quiet --no-keyring --import --import-options import-show /usr/share/keyrings/nginx-archive-keyring.gpg
            echo "deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] http://nginx.org/packages/ubuntu `lsb_release -cs` nginx" | sudo tee /etc/apt/sources.list.d/nginx.list

    - name: Debian - Update & Install nginx
      apt:
        update_cache: true
        pkg:
          - nginx
        state: latest
      when: ansible_os_family == 'Debian'

    - name: Unlink default config and create SSL keys. 
      shell: |
            sudo unlink /etc/nginx/conf.d/default.conf
            sudo openssl req -x509 -nodes -days 1095 -newkey rsa:2048 -keyout /etc/ssl/private/self-signed-key.pem -out /etc/ssl/certs/self-signed-crt.pem -subj "/C=US/ST=Any/L=Anytown/O=decyphertek-io/OU=adminotaur/CN=decyphertek"

    - name: Copy Nginx conf  
      copy:
        src: /etc/ansible/roles/nginx/files/custom.conf
        dest: /etc/nginx/conf.d/custom.conf
        backup: yes  
      register: conf
    - debug: var=conf
    
    - name: Enable & Start Nginx
      service:
        name: nginx
        state: started
        enabled: yes
  

  
