    - name: Add nginx stable repository from PPA and install its signing key on Ubuntu target
      apt_repository:
      repo: ppa:nginx/stable
      state: present
      
    - name: Debian - Update & Install nginx
      apt:
        update_cache: true
        pkg:
          - nginx
        state: latest
      when: ansible_os_family == 'Debian'

    - name: Copy Nginx conf  
      copy:
        src: /etc/ansible/roles/nginx/files/custom.conf
        dest: /etc/nginx/conf.d/custom.conf
        backup: yes  
      register: conf
    - debug: var=conf
    
    - name: Enable & Start Auditd
      service:
        name: nginx
        state: started
        enabled: yes
  

  
