    - name: Add Nginx Offical Repo deb - Ubuntu 22.04 LTS
      apt_repository:
      repo: deb https://nginx.org/packages/ubuntu/ jammy nginx
      state: present

    - name: Add Nginx Offical Repo deb-src - Ubuntu 22.04 LTS
      apt_repository:
      repo: deb-src https://nginx.org/packages/ubuntu/ jammy nginx
      state: present

    - name: Debian - Update & Install nginx
      apt:
        update_cache: true
        pkg:
          - nginx
        state: latest
      when: ansible_os_family == 'Debian'

    - name: Unlink default config and create SSL keys. 
      shell: |
            sudo unlink /etc/nginx/conf.d/default.conf
            sudo openssl req -x509 -nodes -days 1095 -newkey rsa:2048 -keyout /etc/ssl/private/self-signed-key.pem -out /etc/ssl/certs/self-signed-crt.pem -subj "/C=US/ST=Any/L=Anytown/O=decyphertek-io/OU=adminotaur/CN=decyphertek"

    - name: Copy Nginx conf  
      copy:
        src: /etc/ansible/roles/nginx/files/custom.conf
        dest: /etc/nginx/conf.d/custom.conf
        backup: yes  
      register: conf
    - debug: var=conf
    
    - name: Enable & Start Auditd
      service:
        name: nginx
        state: started
        enabled: yes
  

  
