- name: ausearch -f /etc/passwd
  hosts: all
  debugger: on_skipped

  tasks:
  
    - name: Check to see the timedateclt status
      shell: |
        sudo auditctl -w /etc/passwd -p war -k password-file
        sudo ausearch -f /etc/passwd
      register: ausearch
    - debug: var=ausearch
