- name: Check essential services
  hosts: all
  debugger: on_skipped

  tasks:

    - name: Check on Crowdsec.
      service:
        name: crowdsec
        state: started 
        enabled: yes   
      register: crowdsec
    - debug: var=crowdsec
    
    - name: Check on sssd
      service:
        name: sssd
        state: started
        enabled: yes
      register: sssd
    - debug: var=sssd

    - name: Check on Auditd
      service:
        name: auditd
        state: started
        enabled: yes
      register: auditd
    - debug: var=auditd  
