    - name: Debian9 Oscap Scan
      shell: | 
            mkdir /opt/ssg/
            mkdir /opt/ssg-reports/

    - name: Copy Your SSG over. ( Debian 9 In this case )
      copy:
        src: /etc/ansible/roles/oscap-scan-debian9/files/ssg-debian9-ds-1.2.xml
        dest: /opt/ssg/ssg-debian9-ds-1.2.xml
        backup: yes  
      when: ansible_os_family == 'Debian'

    - name: Copy Over CPE Decitionary ( Debian 9)
      copy:
        src: /etc/ansible/roles/oscap-scan-debian9/files/ssg-debian9-ds-1.2.xml
        dest: /opt/ssg/ssg-debian9-ds-1.2.xml
        backup: yes  
      when: ansible_os_family == 'Debian'

    - name: Run an oscap scan and recieve results. 
      shell: | 
            oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_anssi_np_nt28_high /opt/ssg/ssg-debian9-ds-1.2.xml  > /opt/ssg-reports/Debian9-Report.txt
            cat /opt/ssg-reports/Debian9-Report.txt
      register: shell
    - debug: var=shell.stdout_lines

 

            
           



      