    - name: Debian - Update & Oscap
      apt:
        update_cache: true
        pkg:
          - rsyslog
        state: latest
      when: ansible_os_family == 'Debian'

    - name: Enable & Start Rsyslog
      service:
        name: rsyslog
        state: started
        enabled: yes
      when: ansible_os_family == 'Debian'

    

   
 