    
    - name: Terminate Instance IDs
      shell: sudo aws ec2 terminate-instances aws ec2 terminate-instances --instance-ids "{{instance}}"
      register: terminate
    - debug: var=terminate
    