
    - name: 
      shell: |
            rpm -Uvh https://repo.zabbix.com/zabbix/6.0/rhel/8/x86_64/zabbix-release-6.0-4.el8.noarch.rpm
            dnf clean all 
      when: ansible_os_family == 'RedHat'
      register: shell
    - debug: var=shell

    - name: Install Zabbix packages
      dnf:
        name:
          - zabbix-server-mysql 
          - zabbix-web-mysql 
          - zabbix-apache-conf 
          - zabbix-sql-scripts 
          - zabbix-selinux-policy 
          - zabbix-agent 
          - python3-PyMySQL
          - mysql-server
        state: latest
      when: ansible_os_family == 'RedHat'
      register: zabbix
    - debug: var=zabbix

    - name: Set my.cnf /etc
      copy:
        src: /etc/ansible/roles/zabbix-server-install/files/my.cnf
        dest: /etc/my.cnf
        backup: yes

    - name: Set mysql-server.cnf /etc/my.cnf.d
      copy:
        src: /etc/ansible/roles/zabbix-server-install/files/mysql-server.cnf
        dest: /etc/my.cnf.d/mysql-server.cnf
        backup: yes

    - name: Copy Zabbix configuration
      copy:
        src: /etc/ansible/roles/zabbix-server-install/files/zabbix_server.conf
        dest: /etc/zabbix/zabbix_server.conf
        backup: yes

    - name: Zabbix Conf Server
      replace:
        path: /etc/zabbix/zabbix_server.conf
        regexp: 'zabbix_pass'
        replace: '{{zabbix_pass}}'

    - name: Enable & Start Mysql
      service:
        name: mysqld
        state: started
        enabled: yes
      register: mysqld
    - debug: var=mysqld

    - name: Set root user password
      mysql_user:
        name: root
        password: '{{mysql_root_password}}'
        login_user: root
      register: root_pass
    - debug: var=root_pass

    - name: Create new database Named Zabbix
      mysql_db:
        name: zabbix
        state: present
        login_user: root
        login_password: '{{mysql_root_password}}'
      register: zabbix_db
    - debug: var=zabbix_db

    - name: Create database user Zabbix with password and zabbix DB privileges 'WITH GRANT OPTION'
      mysql_user:
        name: zabbix
        password: '{{zabbix_pass}}'
        priv: 'zabbix.*:ALL,GRANT'
        state: present
        login_user: root
        login_password: '{{mysql_root_password}}'
      register: zabbix_user
    - debug: var=zabbix_user

    - name: Shell command utilizing gunzip to set mysql config settings.
      shell: gunzip -d /usr/share/zabbix-sql-scripts/mysql/server.sql.gz

    - name: Import file.sql similar to mysql -u <username> -p <password> < hostname.sql
      mysql_db:
        state: import
        name: zabbix
        target: /usr/share/zabbix-sql-scripts/mysql/server.sql
        login_user: zabbix
        login_password: '{{zabbix_pass}}'
           
    - name: Zabbix - set Global log-bin-trust-function-creators = 0 
      replace:
        path: /etc/my.cnf.d/mysql-server.cnf
        regexp: 'log-bin-trust-function-creators = 1'
        replace: 'log-bin-trust-function-creators = 0'
    
    - name: Shell command utilizing Openssl. 
      shell: |
            openssl req -x509 -nodes -days 1095 -newkey rsa:2048 -keyout /etc/pki/tls/private/apache-selfsigned.key -out /etc/pki/tls/certs/apache-selfsigned.crt -subj "/C=US/ST=Any/L=Anytown/O=decyphertek-io/OU=adminotaur/CN=decyphertek"
            openssl dhparam -out /etc/pki/tls/certs/dhparam.pem 2048 
      register: openssl
    - debug: var=openssl

    - name: Enable & Start Zabbix Server
      service:
        name: zabbix-server
        state: started
        enabled: yes
      register: server
    - debug: var=server

    - name: Enable & Start Zabbix
      service:
        name: zabbix-agent
        state: started
        enabled: yes
      register: agent
    - debug: var=agent

    - name: Enable & Start Apache
      service:
        name: httpd
        state: started
        enabled: yes
      register: apache
    - debug: var=apache

    - name: Enable & Start php-fpm
      service:
        name: php-fpm
        state: started
        enabled: yes
      register: php
    - debug: var=php


### References ###
# https://www.zabbix.com/download?zabbix=6.0&os_distribution=red_hat_enterprise_linux&os_version=8&components=server_frontend_agent&db=mysql&ws=apache
