
    - name: Curl NodeJS Repo
      shell: |
        sudo su -c "curl -fsSL https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key
        curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash - 
      register: curl
    - debug: var=curl
   
    - name: Update & Install Jupyterhub base packages.
      apt:
        update_cache: true
        pkg:
          - nodejs
          - python3-pip
      register: apt
    - debug: var=apt

    - name: Install npm & generate Jupyterhub config
      shell: |
        sudo npm install -g configurable-http-proxy 
        sudo python3 -m pip install jupyterhub 
        sudo python3 -m pip install jupyterlab notebook
        sudo python3 -m pip install PyJWT
        sudo python3 -m pip install oauthenticator
        sudo chmod 700 /etc/ssl/private 
        sudo openssl req -x509 -nodes -days 1095 -newkey rsa:2048 -keyout /etc/ssl/private/private-ssl.key -out /etc/ssl/certs/private-ssl.crt -subj "/C=US/ST=Any/L=Anytown/O=decyphertek-io/OU=adminotaur/CN=decyphertek" 
        sudo jupyterhub --generate-config
      register: install
    - debug: var=install

    - name: Copy juptyerhub_config.yml & backup exisitng.
      copy:
        src: /etc/ansible/roles/jupyterhub/files/jupyterhub_config.py
        dest: /home/ubuntu/jupyterhub_config.py
        owner: root
        group: root
        mode: '0644'
        backup: yes
    
    - name: Copy juptyerhub_config.yml & backup exisitng.
      copy:
        src: /etc/ansible/roles/jupyterhub/files/jupyterhub.service
        dest: /etc/systemd/system/jupyterhub.service
        owner: root
        group: root
        mode: '0644'
        backup: yes

    - name: Start Jupyterhub
      service:
        name: jupyterhub
        state: started 
        enabled: yes   
      register: jupyterhub
    - debug: var=jupyterhub
      
   
     