    - name: Check the info of your instances. 
      shell: sudo aws ec2 describe-instances --query 'Reservations[].Instances[].[State.Name, InstanceId, ImageId, InstanceType, PublicIpAddress, SubnetId, VpcId,Tags[?Key==`Name`]| [0].Value]'
      register: aws_check
    - debug: var=aws_check.stdout
  
    - pause:
        prompt: "What instance do you want to stop"
        echo: yes
      register: result
    - set_fact:
        instance: "{{result.user_input}}"
    - debug:
        var: instance
    
    - name: Stop Instance IDs
      shell: sudo aws ec2 stop-instances --instance-ids "{{instance}}"
      register: stop
    - debug: var=stop
    