- name: Check to see if Zabbix is started. 
  hosts: all
  debugger: on_skipped

  tasks:
    - name: Zabbix - Creates a cron job. 
      cron:  
        name: start zabbix-agent
        job: systemctl start zabbix-agent 
        weekday: "0" 
        minute: "15" 
        hour: "0" 
      register: cron
    - debug: var=cron     

 
