- name: Check to see if Zabbix is started. 
  hosts: all
  debugger: on_skipped

  tasks:
   #Produced no errors, though di not show up under the /etc/cron.d , where is it? ) 
    - name: Zabbix - Creates a cron file under /etc/cron.d 
      cron:  
        name: start zabbix-agent
        job: systemctl start zabbix-agent 
        weekday: "0" 
        minute: "15" 
        hour: "0" 
      register: cron
    - debug: var=cron     

 
