- name: Unattended-upgrades Security Patching
  hosts: all
  debugger: on_skipped

  tasks:
    - name: Run update
      apt:
        update_cache: true
        pkg: 
          - cron-apt
     
    - name: See apt changes
      command: cat /var/log/apt/history.log
      register: cat
    - debug: var=cat.stdout_lines

    - name: List applications installed & Version
      command: sudo apt list --installed
      register: apt 
    - debug: var=apt.stdout_lines
