- name: AWS Module
  hosts: all
  collection: amazon.aws
  
  vars:
    aws_access_key: $AWS_ACCESS_KEY_ID
    aws_secret_key: $AWS_SECRET_ACCESS_KEY

  task:
    - name: Gather information about a single availability zone
      amazon.aws.aws_az_info:
      #aws_access_key: $AWS_ACCESS_KEY_ID
      #aws_secret_key: $AWS_SECRET_ACCESS_KEY
        filters:
          zone-name: us-east-1
