
# Doesnt Work right? When I use the var_prompt to load the api key , it works, via vault, it doesnt? 

- name: Generate text with OpenAI GPT-3
  hosts: localhost
  vars_files:
    - /etc/ansible/vault/variable.vault

  vars_prompt:
    - name: prompt_text
      prompt: "What would you like to ask Chatgpt"
      private: no

  tasks:
    - name: Generate text with OpenAI GPT-3
      uri:
        url: "https://api.openai.com/v1/engines/davinci-codex/completions"
        method: POST
        body_format: json
        headers:
          Content-Type: "application/json"
          Authorization: "Bearer {{ openai_api_key }}"
        body:
          prompt: "{{ prompt_text }}"
          max_tokens: 100
          n: 1
          stop: "\n"
      register: response
    - debug: var=response.json.choices[0].text
