- name: Zabbix Conf Test
  hosts: all
  debugger: on_skipped

  tasks:
    - name: Zabbix Conf Server
      replace: 
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Server=127\.0\.0\.1$'
        replace: 'Server=ip-adress'
        
    - name: Zabbix Conf Active Server
      replace:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^ServerActive=127\.0\.0\.1$'
        replace: '#ServerActve=ip-address'
      
    - name: Zabbix Conf Host Name
      replace:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Hostname=Zabbix server$'
        replace: '#Hostname=hostname-here'
        
