
- name: Zabbix 6.0LTS Server Install
  hosts: all
  vars_files:
    - /etc/ansible/vault/variable.vault

  tasks:
    - name: 
      shell: |
            rpm -Uvh https://repo.zabbix.com/zabbix/6.0/rhel/8/x86_64/zabbix-release-6.0-4.el8.noarch.rpm
            dnf clean all 
      when: ansible_os_family == 'RedHat'
      register: shell
    - debug: var=shell

    - name: Install Zabbix packages
      dnf:
        name:
          - zabbix-server-mysql 
          - zabbix-web-mysql 
          - zabbix-apache-conf 
          - zabbix-sql-scripts 
          - zabbix-selinux-policy 
          - zabbix-agent 
        state: latest
      when: ansible_os_family == 'RedHat'
      register: zabbix
    - debug: var=zabbix

    - name: Create new database Named Zabbix
      mysql_db:
        name:
          - zabbix
      state: present

    - name: Create database user Zabbix with password and zabbix DB privileges 'WITH GRANT OPTION'
      mysql_user:
        name: zabbix@localhost
        password: '{{zabbix_pass}}'
        priv: 'zabbix.*:ALL,GRANT'
        state: present

    - name: Shell command utilizing zcat to set mysql config settings.
      shell: zcat /usr/share/zabbix-sql-scripts/mysql/server.sql.gz | mysql --default-character-set=utf8mb4 -uzabbix -p '{{zabbix_pass}}'
      register: 
    - debug: var=shell 
    
    - name: Zabbix Conf Server
      replace:
        path: /etc/zabbix/zabbix_server.conf 
        regexp: 'DBPassword=password'
        replace: 'DBPassword='{{db_password}}''

     - name: Enable & Start Zabbix Server
       service:
         name: zabbix-server
         state: started
         enabled: yes
       register: zabbix-server
     - debug: var=zabbix-server

     - name: Enable & Start Zabbix
       service:
         name: zabbix-agent
         state: started
         enabled: yes
       register: zabbix-agent
     - debug: var=zabbix-agent

    - name: Enable & Start Apache
       service:
         name: httpd
         state: started
         enabled: yes
       register: apache
     - debug: var=apache

    - name: Enable & Start php-fpm
       service:
         name: php-fpm
         state: started
         enabled: yes
       register: php-fpm
     - debug: var=php-fpm


### References ###
# https://www.zabbix.com/download?zabbix=6.0&os_distribution=red_hat_enterprise_linux&os_version=8&components=server_frontend_agent&db=mysql&ws=apache

# Missing these configs, maybe can set via mysql.cnf
# Enable set global true before running zcat . 
# character set utf8mb4 collate utf8mb4_bin;
# set global log_bin_trust_function_creators = 1;
# Disable after mysql configured
# set global log_bin_trust_function_creators = 0;
# Revisit regex , make sure you dont need delimiters . 