- name: Zabbix 6.0LTS Server Install
  hosts: all
  debugger: on_skipped

  tasks:
    - name: 
      shell: |
            rpm -Uvh https://repo.zabbix.com/zabbix/6.2/rhel/9/x86_64/zabbix-release-6.2-3.el9.noarch.rpm
            dnf clean all 
      when: ansible_os_family == 'RedHat'
      register: shell
    - debug: var=shell

    - name: Install Zabbix packages
      dnf:
        name:
          - zabbix-server-mysql 
          - zabbix-web-mysql 
          - zabbix-nginx-conf 
          - zabbix-sql-scripts 
          - zabbix-selinux-policy 
          - zabbix-agent 
        state: latest
      when: ansible_os_family == 'RedHat'
      register: zabbix
    - debug: var=zabbix

    # Work in Progress:
    # Working on - Mysql & Nginx portion. 