
    - name: Update & Install auditd
      apt:
        update_cache: true
        pkg:
          - auditd
          - audispd-plugins
        state: latest
      when: ansible_facts['os_family'] == "Debian"

    - name: Update & Install auditd
      yum:
        update_cache: true
        pkg:
          - auditd
          - audispd-plugins
        state: latest
      when: ansible_facts['os_family'] == "RedHat"
    
    - name: Update & Install auditd
      dnf:
        update_cache: true
        pkg:
          - auditd
          - audispd-plugins
        state: latest
      when: ansible_facts['distribution'] == "Fedora"

    - name: Copy1 Auditd Rules 
      copy:
        src: /etc/ansible/roles/auditd/files/audit.rules
        dest: /etc/audit/rules.d/audit.rules  
      register: copy1
    - debug: var=copy1 
    
    - name: Copy2 Auditd Rules 
      copy:
        src: /etc/ansible/roles/auditd/files/audit.rules
        dest: /etc/audit/audit.rules  
      register: copy2
    - debug: var=copy2 

    - name: Enable & Start Auditd
      service:
        name: auditd
        state: started
        enabled: yes
      register: auditd
    - debug: var=auditd

  
