    - name: Debian - Update & Install auditd
      apt:
        update_cache: true
        pkg:
          - auditd
        state: latest
      when: ansible_os_family == 'Debian'

    - name: Redhat - Update & Install auditd
      yum:
        name:
          - auditd
          - audispd-plugins
        state: latest
      when: 
        - ansible_os_family == 'RedHat'
        - ansible_distribution != 'Fedora'
     
    - name: Copy Auditd Rules  > rules.d/
      copy:
        src: /etc/ansible/roles/auditd/files/audit.rules
        dest: /etc/audit/rules.d/audit.rules  
        backup: yes  
      register: rules1
    - debug: var=rules1 
    
    - name: Copy Auditd Rules > audit/
      copy:
        src: /etc/ansible/roles/auditd/files/audit.rules
        dest: /etc/audit/audit.rules
        backup: yes    
      register: rules2
    - debug: var=rules2 

    - name: Enable & Start Auditd
      service:
        name: auditd
        state: started
        enabled: yes
  

  
