
    - name: Debian - Update & Install auditd
      apt:
        update_cache: true
        pkg:
          - auditd
          - audispd-plugins
        state: latest
      when: ansible_facts['os_family'] == "Debian"
      register: debian
    - debug: var=debian 

    # Troubleshooting - when command gets stuck at debug?
    #- name: Redhat - Update & Install auditd
      #yum:
        #name:
          #- auditd
          #- audispd-plugins
        #state: latest
      #when: ansible_facts['os_family'] == "RedHat"  
      #register: redhat
    #- debug: var=rehat 
    
    - name: Copy1 Auditd Rules 
      copy:
        src: /etc/ansible/roles/auditd/files/audit.rules
        dest: /etc/audit/rules.d/audit.rules  
      register: rules1
    - debug: var=rules1 
    
    - name: Copy2 Auditd Rules 
      copy:
        src: /etc/ansible/roles/auditd/files/audit.rules
        dest: /etc/audit/audit.rules  
      register: rules2
    - debug: var=crules2 

    - name: Enable & Start Auditd
      service:
        name: auditd
        state: started
        enabled: yes
      register: auditd
    - debug: var=auditd

  
