    - name: Install qemu-kvm & Cockpit.
      apt:
        update_cache: true
        pkg:
          - qemu-kvm 
          - virtinst 
          - libvirt-clients 
          - bridge-utils 
          - libvirt-daemon-system 
          - cockpit
          - podman
          - cockpit-machines
          - cockpit-storaged
          - cockpit-networkmanager
          - cockpit-packagekit
          - cockpit-podman
        state: latest
      when: ansible_os_family == 'Debian'

    - name: Enable & Start LibvirtD.
      service:
        name: libvirtd
        state: started
        enabled: yes
      when: ansible_os_family == 'Debian'

    - name: Enable & Start Cockpit.
      service:
        name: cockpit.socket
        state: started
        enabled: yes
      when: ansible_os_family == 'Debian'
    
    - name: Allow incoming to port 9090.
      ufw:
        rule: allow
        direction: in
        proto: tcp
        port: '9090'
      when: ansible_os_family == 'Debian'