    - name: Install qemu-kvm & Cockpit.
      dnf:
        name:
          - qemu-kvm 
          - qemu-img 
          - libvirt 
          - virt-install 
          - libvirt-client
          - cockpit
          - podman
          - cockpit-machines
          - cockpit-storaged
          - cockpit-networkmanager
          - cockpit-packagekit
          - cockpit-podman
          - cockpit-selinux
          - cockpit-kdump
          - cockpit-sosreport
          - cockpit-composer
          - cockpit-session-recording
          - firewalld 
          - firewall-config
        state: latest
      when: ansible_os_family == 'RedHat'

    - name: Enable & Start LibvirtD.
      service:
        name: libvirtd
        state: started
        enabled: yes

    - name: Enable & Start Cockpit.
      service:
        name: cockpit.socket
        state: started
        enabled: yes
   
    - name: permit traffic in default zone for ssh. 
      ansible.posix.firewalld:
        service: ssh
        permanent: true
        state: enabled

    - name: Permit traffic in default zone for Cockpit.  
      ansible.posix.firewalld:
        port: 9090/tcp
        permanent: true
        state: enabled

    - name: Enable & Firewalld
      service:
        name: firewalld.service
        state: started
        enabled: yes