    - name: Install all current updates
      dnf:
        name: "*"
        state: latest
      when: ansible_os_family == 'RedHat'

    - name: Autoremove unneeded packages installed as dependencies
      dnf:
        autoremove: yes
      when: ansible_os_family == 'RedHat'
            