    - name: Debian - Update & Install Rsyslog
      apt:
        update_cache: true
        pkg:
          - syslog-ng
        state: latest
      when: ansible_os_family == 'Debian'

    - name: Enable & Start Rsyslog
      service:
        name: syslog-ng
        state: started
        enabled: yes
      when: ansible_os_family == 'Debian'

    

   
 