- name: Email Ansible Reports
  hosts: localhost
  debugger: on_skipped
  vars_files:
    - /etc/ansible/vault/variable.vault

  vars:
    - username: '{{username}}' 
    - password: '{{password}}'
 
 # https://github.com/major/ansible-mailgun
 # Or install and setup postfix 
 # https://www.digitalocean.com/community/tutorials/how-to-set-up-a-mail-relay-with-postfix-and-mailgun-on-ubuntu-16-04
  tasks:
    - name: Email Reports
      community.general.mail:
        host: smtp.mailgun.org
        port: 587
        username: '{{username}}'
        password: '{{password}}'
        from: ansible@hal9000
        to: decyphertek@gmail.com
        subject: Ansible-Report
        attach: /etc/ansible/reports/test.txt
        body: 'Welcome to the Matrix, Case.'
      delegate_to: localhost
  

