- name: Show Changes
  hosts: all
  connection: local
  vars_files:
    - /etc/ansible/ansible/vault/palo.vault

  collections:
    - paloaltonetworks.panos

  vars:
    device:
      ip_address: '{{ ip_address }}'
      api_key: '{{ api_key | default(omit) }}'

    session_min_age: 86400

  tasks:
    - name: Check for pending changes
      paloaltonetworks.panos.panos_op:
        provider: '{{ device }}'
        cmd: 'show config list changes'
      register: changes

    - name: Display changes
      debug:
        msg: '{{ changes.stdout | from_json }}'

    - name: Commit changes if needed
      paloaltonetworks.panos.panos_commit:
        provider: '{{ device }}'
      when: >
        (changes.stdout | from_json).response.result.journal is defined and
        (changes.stdout | from_json).response.result.journal.entry | length > 0
