- name:
  hosts: all
  connection: local
  vars_files:
    - /etc/ansible/ansible/vault/palo.vault
      
  collections:
    - paloaltonetworks.panos

  vars:
    device:
      ip_address: '{{ ip_address }}'
      api_key: '{{ api_key | default(omit) }}'

    session_min_age: 86400

  tasks:
    - name: Run show session all command
      paloaltonetworks.panos.panos_op:
        provider: '{{ device }}'
        cmd: '<show><session><all><filter><min-age>{{ session_min_age }}</min-age></filter></all></session></show>'
        cmd_is_xml: True
      register: result

    - name: Output list of sessions to file
      template:
        src: session_report.j2
        dest: '{{ ip_address }}-{{ ansible_date_time.iso8601 }}-session_report.txt'
        mode: '0644'
      vars:
        sessions: '{{ (result.stdout | from_json).response.result.entry }}'
 
