
    - name: Debian - Update & Install UFW
      apt:
        update_cache: true
        pkg:
          - ufw
        state: latest
      when: ansible_os_family == 'Debian'
   
    - name: Allow incoming to port 22
      ufw:
        rule: allow
        direction: in
        proto: tcp
        port: '22'
      when: ansible_os_family == 'Debian'
    
    - name: Enable & Start ufw
      service:
        name: ufw
        state: started
        enabled: yes
      when: ansible_os_family == 'Debian'
    

  
