    - name: Debian - Update & Install UFW
      apt:
        update_cache: true
        pkg:
          - ufw
        state: latest
      when: ansible_os_family == 'Debian'

    - name: Limit incoming SSH connections to avoid brute-force attacks
      ufw:
        rule: limit
        direction: in
        port: '22'
        proto: tcp
      when: ansible_os_family == 'Debian'

    - name: Enable ufw
      ufw:
        state: enabled
      when: ansible_os_family == 'Debian'
    

  
