- name: Gather AWS Ec2 info
  hosts: local
  collections: amazon.aws

  tasks:
    - name: Gather Ec2 info via filters
      amazon.aws.ec2_ami_info:
        filters:
          name: tag-key
          values: name
          query: 'Reservations[*].Instances[*].{Instance:InstanceId,AZ:Placement.AvailabilityZone,Name:Tags[?Key==`Name`]|[0].Value}'
          output: table
      register: aws_ec2
    - debug: var=aws_ec2

