- name: Launch an Ec2 Instance
  hosts: local
  collections: amazon.aws

  tasks:
    - name: Setup an Ec2 instance 
      amazon.aws.ec2_instance:
        name: '{{ resource_prefix }}'
        instance_type: t2.nano
        image_id: "{{ (amis.images | sort(attribute='creation_date') | last).image_id }}"
        wait: yes
        volumes:
          - device_name: /dev/xvda
            ebs:
              volume_size: 30
              delete_on_termination: true
      register: instance