- name: Gather AWS Ec2 info
  hosts: local
  collections: amazon.aws

  tasks:
    - name: Gather Ec2 info via filters
      amazon.aws.ec2_ami_info:
        filters:
          state: available
      register: aws_ec2
    - debug: var=aws_ec2

 
# https://docs.ansible.com/ansible/latest/collections/amazon/aws/ec2_ami_info_module.html
# https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeImages.html