- name: Gather AWS Ec2 info
  hosts: localhost
  collections: amazon.aws

  tasks:
    - name: Gather Ec2 info via filters
      amazon.aws.ec2_ami_info:
        owners: 099720109477
        filters:
          state: available
      register: aws_ec2
    - debug: var=aws_ec2

 