# Currently only works when vars prompt is set. The issue is that you have to run awscli_get info seperately.
# The vars_prompt always runs first, so unable to acquire awscli_get_info to set the varaibles. 
# Replacing - pause and prompt works on stop and terminate instance, doesnt work here when called  multiple times??
# Work in progress......
# https://nixzie.com/ansible_user_input/

- name: Launch an Ec2 Instance interactively
  hosts: localhost
  collections: amazon.aws

  #vars_prompt:
    #- name: username
      #prompt: "What is your username?"
      #private: no
  
  roles:
    - awscli_get_info
    - awscli_launch_ec2

    