- name: Launch an Ec2 Instance interactively
  hosts: localhost
  collections: amazon.aws
  
  # Run aws_info.yaml to get data. 
  vars_prompt:

    - name: region
      prompt: What region whould you like to deploy to?
      private: no

    - name: build
      prompt: What would you like to name the build?
      private: no

    - name: imageid
      prompt: Please enter the Image Id that you want to use.
      private: no 

    - name: type
      prompt: Please enter the instance type - EX-t2.micro, t2.medium , t2.large .
      private: no 

    - name: keyname
      prompt: Please enter just the keyname that you want to use. 
      private: no 

    - name: vpc_subnet
      prompt: Please enter your vpc you would like to use. 
      private: no

    - name: security_group
      prompt: Please Enter your security group.
      private: no
      
  roles:
    - awscli_launch_ec2

    