- name: Delete Net Interface
  hosts: localhost
  collections: amazon.aws

  # Work in progress, need to set eni as a variable and need to output available net interfaces.
  tasks:
    - name: Run an AWS command
      command: sudo aws ec2 delete-network-interface --network-interface-id eni-0000000
      register: aws_ec2
    - debug: var=aws_ec2

 
