- name: Info on Ec2 instances
  hosts: localhost
  connection: local
  gather_facts: true
 
  vars:
    region: us-east-1

  tasks:
    - community.aws.sts_assume_role:
        role_arn: "arn:aws:iam::00000000:role/admin"
        role_session_name: "ansible"
      register: assumed_role
    - debug: var=assumed_role
    - name: Gather ec2 info
      community.aws.ec2_instance_info:
        filters:
          instance-state-name: [ "running"]
      register: ec2_instance_info
    - debug: var=ec2_instance_info

    #- name: Gather information about running instances
     # community.aws.ec2_instance_info:
       # filters:
         # instance-state-name: [ "running"]
    #- amazon.aws.ec2_vol_info:  
    #- debug_botocore_endpoint_logs: yes 

  # Block is a Group of Tasks combined together
    #- name: Get Info Block
      #block: 
        #- name: Get Running instance Info 
         # ec2_instance_info:
          #register: ec2info 
        #- name: Print info
          #debug: var="ec2info.instances"
