- name: Gather AWS Info
  hosts: local
  connection: local

  vars:
    boto_profile: aws_profile

  tasks:
    - ec2_snapshot_info:
        #filters:
          #"tag:Name": securitybackups
      register: ec2_snapshot_info
    - debug: var=ec2_snapshot_info
