- name: Take snapshot of  AWS volume 
  hosts: localhost
  collections: amazon.aws

  # Work in progress... Need to set volume ID as a variable and list available volumes. 
  tasks:
  - name: Taking snapshot ...
    amazon.aws.ec2_snapshot:
      region: us-east-1
      volume_id: i-000000000
      description: snapshot of EC2 volume
    register: snapshot_output
  - debug:
      var: snapshot_output

