- name: Gather AWS Info
  hosts: local
  connection: local

  tasks:
    - name: Aws Cli - aws ssm describe-instance-information
      command: aws ssm describe-instance-information
      register: aws_ssm
    - debug: var=aws_ssm



