- name: Gather AWS Info
  hosts: localhost
  collections: amazon.aws

  tasks:
    - name: Aws Cli - aws ssm describe-instance-information
      command: sudo aws ssm describe-instance-information
      register: aws_ssm
    - debug: var=aws_ssm



