- name: Gather AWS Info
  hosts: localhost
  collections: amazon.aws

  tasks:
    - name: Run an AWS command
      command: sudo aws ec2 describe-instances
      register: aws_ec2
    - debug: var=aws_ec2
