---
  - name: Test s3
    hosts: localhost
    collections: amazon.aws

    tasks:
      - name: Create new bucket
        amazon.aws_s3:
          bucket: ansible-test
          mode: create
          region: us-east-1
