- name: Sanity check patching config
  hosts: all
  debugger: on_skipped

  tasks:

    - name: Check if patches are being applied and configs are correct. 
      shell: |
        cvescan
        lsb_release -a
        timedatectl status
        tail -n 15 /var/log/apt/history.log
      register: shell
    - debug: var=shell.stdout_lines    

