- name: Install & run cvescan
  hosts: all
  debugger: on_skipped

  tasks:
    #- name: Update & Install Snapd 
     # apt:
        #update_cache: true
        #pkg: 
          #- snapd

    - name: Install cvescan
      command: sudo snap install cvescan  
           
    - name: Run cvescan report
      shell: | 
        cvescan > cvescan.txt
        cat cvescan.txt
      register: shell
    - debug: var=shell
 
    #- name: cvescan report
      #command: cat cvescan.csv
      #register: cat
    #- debug: var=cat
