- name: Unattended-upgrades Security Patching
  hosts: all
  debugger: on_skipped

  tasks:
    - name: Update & Install unattended-upgrades
      apt:
        update_cache: true
        pkg:
          - unattended-upgrades
          - apt-listchanges
          - debsums

    - name: Activate Unattended Upgrades
      shell: sudo dpkg-reconfigure -plow unattended-upgrades | echo "yes"
      register: dpkg
    - debug: var=dpkg.stdout_lines

    - name: 50unattended-upgrades Config -  AutoFixInterruptedDpkg
      replace:
        path: /etc/apt/apt.conf.d/50unattended-upgrades
        regexp: '//Unattended-Upgrade::AutoFixInterruptedDpkg "false";'
        replace: 'Unattended-Upgrade::AutoFixInterruptedDpkg "true";'
      register: replace
    - debug: var=replace

    - name: 50unattended-upgrades Config -  mail
      replace:
        path: /etc/apt/apt.conf.d/50unattended-upgrades
        regexp: '//Unattended-Upgrade::Mail "root";'
        replace: 'Unattended-Upgrade::Mail "root";'
      register: replace
    - debug: var=replace

    - name: 50unattended-upgrades Config -  Remove-Unused-Kernel-Packages
      replace:
        path: /etc/apt/apt.conf.d/50unattended-upgrades
        regexp: '//Unattended-Upgrade::Remove-Unused-Kernel-Packages "false";'
        replace: 'Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";'
      register: replace
    - debug: var=replace

    - name: 50unattended-upgrades Config -  Remove-Unused-Dependencies
      replace:
        path: /etc/apt/apt.conf.d/50unattended-upgrades
        regexp: '//Unattended-Upgrade::Remove-Unused-Dependencies "false";'
        replace: 'Unattended-Upgrade::Remove-Unused-Dependencies "true";'
      register: replace
    - debug: var=replace

    - name: 50unattended-upgrades Config - Reboots
      replace:
        path: /etc/apt/apt.conf.d/50unattended-upgrades
        regexp: '//Unattended-Upgrade::Automatic-Reboot "false";'
        replace: 'Unattended-Upgrade::Automatic-Reboot "false";'
      register: replace
    - debug: var=replace

    - name: Enable apt-daily.timer
      service:
        name: apt-daily.timer
        state: started

    - name: Enable apt-daily-upgrade.timer
      service:
        name: apt-daily-upgrade.timer
        state: started

 
          

