  vars_prompt:

    - name: build
      prompt: What would you like to name the build?
      private: no

    - name: imageid
      prompt: Please enter just the Image Id that you want to use. ami-0000000 (image1)  ,ami-00000000 (image2) , or ami-0000000 (image3) ?
      private: no 

    - name: vpc_subnet
      prompt: Please enter your vpc you would like to use. 
      private: no

    - name: security_group
      prompt: Please Enter your security group.
      private: no
      
  tasks:
    - name: Setup an Ec2 instance 
      amazon.aws.ec2_instance:
        aws_profile: default
        name: "{{build}} "
        image_id: "{{imageid}}"
        instance_type: t2.medium
        key_name: "keyname"
        vpc_subnet_id: "{{vpc_subnet}}"
        security_group: 
        network:
          assign_public_ip: true
        wait: yes
        # Optional : Additional Volumes + root volume
        #volumes:
          #- device_name: /dev/xvda
            #ebs:
              #volume_size: 30
              #delete_on_termination: true
        tags:
          Environment: 
      register: instance
    - debug: var=instance