    - name: Awscli - 
      shell: sudo aws sts get-caller-identity --query "Account" | grep -o '[[:digit:]]*' 
      register: aws_account
    - debug: var=aws_account.stdout

    - name: Awscli - Get Security Groups , VPCS , and AMIs
      shell: |
            sudo aws ec2 describe-security-groups --query "SecurityGroups[*].{Name:GroupName,ID:GroupId}"
            sudo aws ec2 describe-subnets | grep -E ' Value:|CidrBlock:|VpcId:|SubnetId'
            sudo aws ec2 describe-key-pairs
            sudo aws ec2 describe-images --owners "{{aws_account.stdout}}" --query 'Images[*].[ImageId,Name]' | grep "-"
      ignore_errors: true
      register: aws_info
    - debug: var=aws_info.stdout

    
    