    - name: Awscli - 
      command: sudo aws sts get-caller-identity --query "Account"
      register: aws_account
    - debug: var=aws_account

    - name: Awscli - Get Security Groups
      command: sudo aws ec2 describe-security-groups --query "SecurityGroups[*].{Name:GroupName,ID:GroupId}"
      register: aws_sg
    - debug: var=aws_sg

    - name: Awscli - Get Vpcs
      command: sudo aws ec2 describe-vpcs
      register: aws_vpcs
    - debug: var=aws_vpcs

    
    