- name: Jupyterhub Install & SSSD
  hosts: all
  debugger: on_skipped

  tasks:
    - name: Curl NodeJS Repo
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_17.x | sudo -E bash - 
      register: shell-1
    - debug: var=shell-1
   
    - name: Update & Install Jupyterhub base packages.
      apt:
        update_cache: true
        pkg:
          - nodejs
          - python3-pip
      register: apt
    - debug: var=apt

    - name: Install npm & generate Jupyterhub config
      shell: |
        sudo npm install -g configurable-http-proxy 
        sudo python3 -m pip install jupyterhub 
        sudo python3 -m pip install jupyterlab notebook
        sudo python3 -m pip install PyJWT
        sudo python3 -m pip install oauthenticator
        sudo chmod 700 /etc/ssl/private 
        sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/private-ssl.key -out /etc/ssl/certs/private-ssl.crt 
        sudo jupyterhub --generate-config
      register: shell-2
    - debug: var=shell-2

    - name: Copy juptyerhub_config.yml & backup exisitng.
      copy:
        src: /home/repo/playbooks/jupyterhub/jupyterhub-config/jupyterhub_config.py
        dest: /home/ubuntu/jupyterhub_config.py
        owner: root
        group: root
        mode: '0644'
        backup: yes

   
        
     
    

