    - name:
      shell: |
            sudo dpkg --configure -a
            sudo apt install -f 
            
    - name: Debian - Update , Upgrade , Autoclean , Autoremove, & Recommendations=no . 
      apt:
        update_cache: yes
        upgrade: yes
        autoclean: yes
        autoremove: yes
        install_recommends: no