    - name: Debian - Fix any broken installs.
      shell: |
            sudo dpkg --configure -a
            sudo apt install -f 
      when: ansible_os_family == 'Debian'
            
    - name: Debian - Update & Upgrade 
      apt:
        update_cache: yes
        upgrade: yes
        install_recommends: no
      when: ansible_os_family == 'Debian'

    - name: Remove old packages
      shell: |
            sudo apt autoremove -y
            sudo apt autoclean -y