    - name:
      shell: |
            sudo dpkg --configure -a
            sudo apt install -f 
            
    - name: Upgrade the OS (apt-get dist-upgrade)
      apt:
        update_cache: yes
        upgrade: yes
        autoclean: yes
        autoremove: yes
        install_recommends: no