    - name: Debian - Fix any broken installs.
      shell: |
            sudo dpkg --configure -a
            sudo apt install -f 
      when: ansible_os_family == 'Debian'
            
    - name: Debian - Update , Upgrade , Autoclean , Autoremove, & Recommendations=no . 
      apt:
        update_cache: yes
        upgrade: yes
        install_recommends: no
      when: ansible_os_family == 'Debian'